export const MEMO_SET = 'MEMO_SET'
export const MEMOS_INIT = 'MEMOS_INIT'
export const MEMOS_ADD = 'MEMOS_ADD'
export const MEMOS_SET = 'MEMOS_SET'
export const MEMOS_REMOVE = 'MEMOS_REMOVE'
export const USER_INIT = 'USER_INIT'
export const USER_SET = 'USER_SET'
