export const ART_SET = 'ART_SET'
export const ARTS_INIT = 'ARTS_INIT'
export const ARTS_ADD = 'ARTS_ADD'
export const ARTS_SET = 'ARTS_SET'
export const ARTS_REMOVE = 'ARTS_REMOVE'
export const USER_INIT = 'USER_INIT'
export const USER_SET = 'USER_SET'
